trigger:
  - main

pool:
  name: 'Default'  # This refers to the agent pool, ensure that your agent is in this pool
  demands:
    - agent.name -equals self-hosted-agent  # Replace this with the exact name of your self-hosted agent

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet build
    displayName: 'Build the project'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
