trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet build
    displayName: 'Build the project'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
